import type { Metadata } from "next";

import "./globals.css";

import Navbar from "@/components/navbar/navbar";
import { gilory } from "@/fonts/gilory";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body className={gilory.className + " flex min-h-[100dvh]"}>
        <Navbar />
        <div className="flex-1 pt-40 md:pt-28">{children}</div>
      </body>
    </html>
  );
}
